In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: C:\Users\user1\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

שאלה 1

In [3]:
arr = np.random.randint(1, 50, size = (10))
arr

array([26, 45, 15, 15, 15, 23,  5,  7,  8,  1], dtype=int32)

In [4]:
np.mean(arr)

np.float64(16.0)

שאלה 2

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
arr2 = np.array([[8, 9, 10], [11, 12, 13], [14, 15, 16]])

In [9]:
result = arr1 + arr2

In [10]:
np.mean(result)

np.float64(16.333333333333332)

שאלה 3

In [12]:
arr = np.random.randint(1, 100, size = (20))
arr

array([66, 92, 14,  3, 95, 70, 71, 23, 51, 80, 18, 36, 41, 37,  2,  8,  1,
       63, 90, 68], dtype=int32)

In [15]:
result = arr[arr > 50]
result

array([66, 92, 95, 70, 71, 51, 80, 63, 90, 68], dtype=int32)